### PR TITLE
Updates to README and converted NEWS in to CHANGELOG.md with improvements. Minor tweak to the licence have been made, now using https.

### PR DESCRIPTION
**Pull request by Jacalz**
A lot of things have been reworked to look  better on for example github :+1:

### CODE REVIEW

**Comment by Jacalz** [comment]
Hi @dvdhrm and thanks for the review. I will see to get your comments addressed in the coming days.
Anyway here are the answers to you questions:
- Will do that, did not know how to do it before and thank you very much for the instructions 🙂
- Will see to get that fixed...
- Basically just thought it sounded better, will revert that back, let’s follow the gnu heard.
- I did those changes myself indeed, will check if I can update it there but I don’t really know where to do that sadly.
- I had a project that used .txt so I just thought I was better to have a file ending, will revert this change.
- I was intending to squash the commits after getting the review 😉

I will probably put in the effort to redo them completely then, just kept the old style because I wanted it to look good for users just looking through a normal text editor. I know that the Linux world can be a bit retro some times 😂 Anyway, will see to get all these changes done before Christmas 🎄

**Comment by Jacalz** [comment]
Everything from your review should be addressed now :+1: @dvdhrm

**Comment by dvdhrm** [comment]
I fixed the copy-paste typo myself, as well as 3 minor indentations. I hope you don't mind. I cherry-picked the patch and pushed to master.

Thanks a lot!

**Comment by Jacalz** [comment]
Thanks for fixing those up, I missed the email notification due to the holidays, sorry bout that. Happy to contribute, and Happy New Years to you all 🍾

**Pull request closed without merging**
