### PR TITLE
protocol: use enums where it makes sense

### PR DESCRIPTION
**Pull request by Keruspe**
Just seemed to make sense for those

### CODE REVIEW

**Comment by dvdhrm** [comment]
Can we please turn all of them into enums? Lets avoid preprocessor use for the sake of better debugging, and use enums for single bits as well.

**Comment by Keruspe** [comment]
Sure, wasn't sure whether we wanted to do that for bitmasks too or not.

**Comment by teg** [comment]
No need to name these things though? Could all be anonymous.

**Comment by Keruspe** [comment]
Should the flags be anonymous or all of the enums?

**Comment by dvdhrm** [comment]
You can leave all of them anonymous. C does not have real type-safety on those, so we avoided using them so far.

**Comment by Keruspe** [comment]
Should be ok now

**Pull request merged**
