### PR TITLE
Fix CI build, musl libc build

### PR DESCRIPTION
**Pull request by bluca**
NOTE: build-tested only, please triple check, especially the move of the last assert. It looks fine from this angle, but I am not familiar enough with the codebase.

### CODE REVIEW

**Comment by dvdhrm** [comment]
Looks all good. The "static_assert" definition of ISO-C11 is just stupid, I hate working around it... Anyway, I am on hiatus until 2020, so no laptop to fix the stuff myself. @teg, can you sync the submodules? `git submodule update --remote` should be fine here.

Otherwise, this series looks good! Thanks a lot. Only thing I did not check is whether the comments have to be moved with the static-assert or whether they are fine as they are.

**Comment by bluca** [comment]
No problem! I have updated the submoule - just the one that was failing. Git is showing the diffstat, but the commit is actually changing the submodule commit id:

```
$ git show HEAD^^
commit d349ea09c1333784522ed32010afc1cde2b73e18
Author: Luca Boccassi <bluca@debian.org>
Date:   Sat Oct 26 11:48:16 2019 +0100

    Update c-dvar submodule to fix CI error
    
    Signed-off-by: Luca Boccassi <bluca@debian.org>

diff --git a/subprojects/c-dvar b/subprojects/c-dvar
index db7d27d..9e1a5b4 160000
--- a/subprojects/c-dvar
+++ b/subprojects/c-dvar
@@ -1 +1 @@
-Subproject commit db7d27de5cff7f5599217308ba1769d4ca97b2a2
+Subproject commit 9e1a5b4363aaece7169df2b2852944a1434b2df5
```

Would you like me to update the other submodules too?

**Comment by dvdhrm** [comment]
I know, I know. All looks good! I just dont want to merge anything from my phone with no way to recover from any issues. @teg will probably be back to work on Monday and merge the outstanding PRs. Just wanted to let him know to also sync the other submodules, just to be sure.

**Comment by bluca** [comment]
Ah ok, no problem at all - sorry, I misunderstood your comment. Thanks!

**Comment by dvdhrm** [comment]
I am back, and I updated the submodules, CI, etc. out of pure habit. I totally forgot that your PR included fixes for them, I am sorry!

I picked up the musl-libc fix and will push it in a minute!

Thanks a lot for the PR, and again sorry for ignoring your build-system fixes!

**Comment by bluca** [comment]
No problem, thanks!

**Pull request closed without merging**
